### ISSUE TITLE
New planet map, can’t find the ores to progress.

### ISSUE THREAD

**Issue by TheJudger501** [w1-BeyeK/rl_mindustry#2]
I was trying the Real Life Mod but can’t find any of the new ores so it’s impossible for me to progress. Is it because the maps changed into the planet style?

**Comment by killerspike01** [comment]
the taianium covenge get hidden when i using this mod

**Comment by SakuraLilly** [comment]
Since V6 you can only use the mod in custom maps. We have no planet at this time.
